### ISSUE TITLE
Related to image coding

### ISSUE THREAD

**Issue by JennaHaze** [putaindecode/fix-all-the-things#17]
class="ex_link" 

Can somebody please tell what does this above mentioned code mean ? It is used in image coding. I've seen it with rel="nofollow" but I don't know what this code is used for. Kindly help in this regard.

**Comment by kud** [comment]
You're not on the right project. This project is used to file bugs on projects which do not have public bugtracker.

**Comment by JennaHaze** [comment]
Ummm I just saw this tag here https://www.plurk.com/hazekraze in the coding of this page. Can u please let me know what does it mean being used here ?

**Comment by kud** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors
